# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lang',
            field=models.CharField(default='english', max_length=100),
        ),
    ]
