# Generated by Django 2.0 on 2017-12-22 15:12

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shows", "0001_initial")]

    operations = [TrigramExtension()]
